# Generated by Django 5.0.6 on 2024-08-15 09:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AppEduInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eduLevel', models.CharField(max_length=20)),
                ('InstName', models.CharField(max_length=80)),
                ('address', models.CharField(max_length=200)),
                ('enrollment', models.CharField(max_length=15)),
                ('program', models.CharField(max_length=20)),
                ('year', models.IntegerField()),
                ('percent', models.DecimalField(decimal_places=2, max_digits=3)),
                ('passingYear', models.IntegerField()),
                ('marksheet', models.FileField(default=None, max_length=500, null=True, upload_to='media/marksheet/')),
                ('username', models.ForeignKey(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AppPerInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullName', models.CharField(max_length=50)),
                ('dob', models.DateField()),
                ('gender', models.CharField(max_length=10)),
                ('category', models.CharField(max_length=10)),
                ('caste_certi_no', models.CharField(max_length=15)),
                ('aadhar', models.CharField(max_length=12)),
                ('father', models.CharField(max_length=50)),
                ('phone', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('income', models.IntegerField()),
                ('address', models.CharField(max_length=200)),
                ('pincode', models.CharField(max_length=7)),
                ('username', models.ForeignKey(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
