# Generated by Django 5.0.6 on 2024-08-15 10:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='appeduinfo',
            name='marksheet',
            field=models.FileField(default=None, max_length=500, null=True, upload_to='marksheet/'),
        ),
        migrations.CreateModel(
            name='AppBanInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accHolderName', models.CharField(max_length=50)),
                ('accNumber', models.CharField(max_length=30)),
                ('bankName', models.CharField(max_length=50)),
                ('branchName', models.CharField(max_length=50)),
                ('ifcs', models.CharField(max_length=12)),
                ('username', models.ForeignKey(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AppDocInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('casteCerti', models.FileField(default=None, max_length=500, null=True, upload_to='Caste_Certificate/')),
                ('incomeCerti', models.FileField(default=None, max_length=500, null=True, upload_to='Income_Certificate/')),
                ('aadhaar', models.FileField(default=None, max_length=500, null=True, upload_to='Aadhaar/')),
                ('photo', models.FileField(default=None, max_length=500, null=True, upload_to='Photographs/')),
                ('sign', models.FileField(default=None, max_length=500, null=True, upload_to='Signature/')),
                ('addmissionLetter', models.FileField(default=None, max_length=500, null=True, upload_to='Admission_Letter/')),
                ('username', models.ForeignKey(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
