# Generated by Django 5.0.6 on 2024-08-15 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_alter_appeduinfo_marksheet_appbaninfo_appdocinfo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appbaninfo',
            old_name='ifcs',
            new_name='ifsc',
        ),
    ]
