# Generated by Django 5.0.6 on 2024-08-15 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0004_formstatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formstatus',
            name='message',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
