# Generated by Django 5.0.6 on 2024-08-16 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0006_hodapprove_hodreject_principalapprove_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hodreject',
            old_name='RejectMessage',
            new_name='rejectMessage',
        ),
    ]
